apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service11
  labels:
    name: config-service11
  namespace: default
data:
  conf.json: '{"processes":10,"logging":false,"protocol":"grpc","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE11},"threads":1}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service11
  namespace: default
  labels: {}
spec:
  selector:
    matchLabels:
      app: service11
      version: ''
  replicas: 1
  template:
    metadata:
      labels:
        app: service11
        version: ''
      annotations: {}
    spec:
      nodeName: ${WORKER_NODE_SERVICE11}
      containers:
        - name: app
          image: yizhengx/mesh:synthetic
          imagePullPolicy: Always
          env:
            - name: APP_NAME
              value: service
            - name: CONF
              value: /usr/src/emulator/config/conf.json
            - name: GOMEMLIMIT
              value: '1024000000'
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /usr/src/emulator/config
              name: config-data-volume
      volumes:
        - name: config-data-volume
          configMap:
            name: config-service11
---
apiVersion: v1
kind: Service
metadata:
  name: service11
  namespace: default
  labels: {}
  annotations:
    http: /
spec:
  selector:
    app: service11
  ports:
    - name: grpc
      port: 80
      targetPort: 5000
