apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
spec:
  values:
    global:
      proxy:
        resources:
          requests:
            null
          limits:
            null
  meshConfig:
    defaultConfig:
      concurrency: 4