apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb-profile
  name: mongodb-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb-profile
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb-profile
    spec:
      containers:
        - image: mongo:4.4.6
          name: hotel-reserv-profile-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
          volumeMounts:
            - mountPath: /data/db
              name: profile
        - name: istio-proxy
          image: docker.io/alicesong2002/modified_istio_proxy:v11.5
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /usr/src
            name: linux-headers
          - name: tmp
            mountPath: /tmp
          resources:
            limits:
              memory: "3000Mi"
            requests:
              memory: "3000Mi"
      hostname: profile-db
      restartPolicy: Always
      volumes:
        - name: profile
          persistentVolumeClaim:
            claimName: profile-pvc
        - name: tmp
          emptyDir: {}
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: linux-headers
          hostPath:
            path: /usr/src
            type: Directory
status: {}
