apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: search-l4-policy
  namespace: hotel
spec:
  podSelector:
    matchLabels:
      app: hotel
      io.kompose.service: search

  policyTypes:
  - Egress

  egress:
  - to:
    - podSelector:
        matchLabels:
          app: geo
    ports:
    - protocol: TCP
      port: 8083

  - to:
    - podSelector:
        matchLabels:
          app: rate
    ports:
    - protocol: TCP
      port: 8085