apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: memcached-rate
  name: memcached-rate
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: memcached-rate
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
        sidecar.istio.io/statsInclusionPrefixes: cluster.outbound,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grp,listener,connection_manager
        sidecar.istio.io/statsInclusionRegexps: http.*
      creationTimestamp: null
      labels:
        io.kompose.service: memcached-rate
    spec:
      containers:
        - env:
            - name: MEMCACHED_CACHE_SIZE
              value: "128"
            - name: MEMCACHED_THREADS
              value: "2"
          image: memcached
          name: hotel-reserv-rate-mmc
          ports:
            - containerPort: 11211
          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 1000m
        - name: istio-proxy
          image: docker.io/alicesong2002/modified_istio_proxy:v11.6
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          volumeMounts:
          - mountPath: /lib/modules
            name: lib-modules
          - mountPath: /usr/src
            name: linux-headers
          - name: tmp
            mountPath: /tmp
          resources:
            limits:
              memory: "3000Mi"
            requests:
              memory: "3000Mi"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: lib-modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: linux-headers
        hostPath:
          path: /usr/src
          type: Directory
      restartPolicy: Always
status: {}