apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service1-locality
  namespace: default
spec:
  host: service1.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        distribute:
        - from: node-2/*
          to:
            "node-2/*": 100