apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-controlplane
spec:
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 1Gi