apiVersion: v1
kind: ConfigMap
metadata:
    name: config-service13
    labels:
        name: config-service13
    namespace: default
data:
    conf.json: '{"processes":10,"logging":false,"protocol":"http","endpoints":[{"name":"endpoint1","execution_mode":"sequential","cpu_complexity":{"execution_time":${PROCESSING_TIME_SERVICE13},"threads":1},"network_complexity":{"forward_requests":"synchronous","response_payload_size":256,"called_services":[{"service":"service14","port":80,"endpoint":"endpoint1","protocol":"http","traffic_forward_ratio":1,"request_payload_size":512,"probability":0}]}}]}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: service13
    namespace: default
    labels: {}
spec:
    selector:
        matchLabels:
            app: service13
            version: ""
    replicas: 1
    template:
        metadata:
            labels:
                app: service13
                version: ""
            annotations: {}
        spec:
            nodeName: "${WORKER_NODE_SERVICE13}"
            containers:
                - name: istio-proxy
                  image: docker.io/alicesong2002/modified_istio_proxy:v19.3
                  securityContext:
                    allowPrivilegeEscalation: true
                    privileged: true
                    capabilities:
                      add: ["SYS_ADMIN"]
                  volumeMounts:
                  - mountPath: /lib/modules
                    name: lib-modules
                  - mountPath: /usr/src
                    name: linux-headers
                  - name: tmp
                    mountPath: /tmp
                  resources:
                    limits:
                      memory: "3000Mi"
                    requests:
                      memory: "3000Mi"
                - name: app
                  image: yizhengx/mesh:synthetic
                  imagePullPolicy: Always
                  env:
                    - name: APP_NAME
                      value: service
                    - name: CONF
                      value: /usr/src/emulator/config/conf.json
                    - name: GOMEMLIMIT
                      value: "1024000000"
                  ports:
                    - containerPort: 5000
                  volumeMounts:
                    - mountPath: /usr/src/emulator/config
                      name: config-data-volume
                  readinessProbe:
                    httpGet:
                        path: /
                        port: 5000
                    initialDelaySeconds: 5
                    periodSeconds: 1
            volumes:
                - name: tmp
                  emptyDir: {}
                - name: lib-modules
                  hostPath:
                    path: /lib/modules
                    type: Directory
                - name: linux-headers
                  hostPath:
                    path: /usr/src
                    type: Directory
                - name: config-data-volume
                  configMap:
                    name: config-service13
---
apiVersion: v1
kind: Service
metadata:
    name: service13
    namespace: default
    labels: {}
    annotations:
        http: /
spec:
    selector:
        app: service13
    ports:
        - name: http
          port: 80
          targetPort: 5000