apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: geo-l4-policy
  namespace: hotel
spec:
  endpointSelector:
    matchLabels:
      io.kompose.service: geo

  egress:
  - toEndpoints:
    - matchLabels:
        io.kompose.service: mongodb-geo
    toPorts:
    - ports:
      - port: "27017"
        protocol: TCP
    
  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
      - ports:
          - port: "53"
            protocol: UDP
        rules:
          dns:
            - matchPattern: "*"

  - toEntities:
    - kube-apiserver
    - world
    - host