apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: search-l4-policy
  namespace: hotel
spec:
  endpointSelector:
    matchLabels:
      io.kompose.service: search
  
  egress:
  - toEndpoints:
    - matchLabels:
        io.kompose.service: geo
    toPorts:
    - ports:
      - port: "8083"
        protocol: TCP
    
  - toEndpoints:
    - matchLabels:
        io.kompose.service: rate
    toPorts:
    - ports:
      - port: "8084"
        protocol: TCP

  - toEndpoints:
    - matchLabels:
        io.kubernetes.pod.namespace: kube-system
        k8s-app: kube-dns
    toPorts:
      - ports:
          - port: "53"
            protocol: UDP
        rules:
          dns:
            - matchPattern: "*"

  - toEntities:
    - kube-apiserver
    - world
    - host